In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
df = pd.read_csv('dummy_house_prices.csv')

In [5]:
df.head()

,Id,LotArea,OverallQual,YearBuilt,GrLivArea,GarageCars,TotalBsmtSF,SalePrice
0,1,9270,2,1950,3523,2,1300,604616.781310
1,2,2860,3,1938,1209,3,725,502477.383336
2,3,7390,1,1950,1723,0,1243,521253.969689
3,4,7191,8,1969,3013,1,1928,718218.320166
4,5,13964,3,1905,1612,3,1049,549081.220541

In [7]:
X = df.drop(['SalePrice', 'Id'], axis=1)

In [9]:
df.head()

,Id,LotArea,OverallQual,YearBuilt,GrLivArea,GarageCars,TotalBsmtSF,SalePrice
0,1,9270,2,1950,3523,2,1300,604616.781310
1,2,2860,3,1938,1209,3,725,502477.383336
2,3,7390,1,1950,1723,0,1243,521253.969689
3,4,7191,8,1969,3013,1,1928,718218.320166
4,5,13964,3,1905,1612,3,1049,549081.220541

In [11]:
X.head()

   LotArea  OverallQual  YearBuilt  GrLivArea  GarageCars  TotalBsmtSF
0     9270            2       1950       3523           2         1300
1     2860            3       1938       1209           3          725
2     7390            1       1950       1723           0         1243
3     7191            8       1969       3013           1         1928
4    13964            3       1905       1612           3         1049

In [33]:
y = df['SalePrice']

Train the dataset in the next step

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

Using of linear Regression

In [19]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

Making a predcition

In [21]:
y_pred = model.predict(X_test)

In [23]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

In [25]:
print("Model performance")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"R² Score: {r2:.4f}")

Model performance
Root Mean Squared Error (RMSE): 22193.43
R² Score: 0.9281

In [31]:
sample = X_test.iloc[0:1]
pred_price = model.predict(sample)
print(f" Predicted Sale Price for sample house: ${pred_price[0]:.2f}")

 Predicted Sale Price for sample house: $626579.65